# handlers file for VictoriaMetrics
---
- name: restart vmselect
  become: true
  systemd:
    daemon_reload: true
    name: vmselect
    state: restarted

- name: restart vminsert
  become: true
  systemd:
    daemon_reload: true
    name: vminsert
    state: restarted

- name: restart vmstorage
  become: true
  systemd:
    daemon_reload: true
    name: vmstorage
    state: restarted

- name: restart victoriametrics
  become: true
  systemd:
    daemon_reload: true
    name: victoriametrics
    state: restarted
